default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development_rd
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test_rd
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: blog_production_rd
  username: postgres
  password: postgres
  host: localhost
  port: 5432
